// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stsilkgjeathqtrbnrod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0c2lsa2dqZWF0aHF0cmJucm9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTg5NzIsImV4cCI6MjA2ODM5NDk3Mn0.b5aziNakqPzEdcFxBut7iR_SfPaKR5BC76sgmxZYkZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});